title: Yingjian Liang
# Comment out url when working locally to resolve base urls correctly
url: https://liyu567-hub.github.io
baseurl: /yingjianliang.github.io


# Owner/author information
owner:
  name: Yingjian Liang
  avatar: avatar.jpg
  email: yingjianliang@hrbmu.edu.cn
  github: LarrySimingDeng
  linkedin: larry-deng-317b92360
  scholar: https://scholar.google.com/citations?hl=en&user=aKyLtgsAAAAJ
  researchgate: https://www.researchgate.net/profile/Siming-Deng-3

# https://search.google.com/search-console/ownership
google_verify: "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"

# Links to include in top navigation
links:
  - title: About Me
    url: /
  - title: Publications
    url: /publications/
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai
future: true
highlighter: rouge

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
